version: '3.7'

services:

  apps:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']  
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@dataset-db:5432/dataset_dev  
      - DATABASE_TEST_URL=postgresql://postgres:postgres@dataset-db:5432/dataset_test 
    depends_on: 
      - dataset-db  

  dataset-db:  
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres